### PR TITLE
Add initial logic for tiling base zarr array

### PR DESCRIPTION
**Pull request by manzt**
Lots of the logic here is from what you shared before. I've been converting a few different arrays to pyramids for vitessce and thought I'd share the script that has been working well for me. 

For now I envision a set of `converters` that can generate the `base` zarr array, and then using an optional pyramid/tiler attribute to generate the downsampled versions of the data. This `base` array should contain all the metadata from the original images, and then children/downsampled versions will just be the arrays. We could generate generate a hash and store this as a key on the base array as well as all the children, but saving all the metadata to all the downsampled arrays seems redundant. Not sure what your thoughts are here. 

The current PR adds a _very_ minimal cli with the current interface. It expects the argument to the command to be the base array path.

```
.
└── dataset.zarr/
    ├── .zgroup
    └── base
        ├── .zarray
        ├── .zattrs
        ├── 0.0.0
        └── ...etc
```

```bash
$ pip install -e .
$ img2zarr create-pyramid dataset.zarr/base # [--tile_size, --max_level]
```

and will generate a group in the same directory `downsampled` with the other zarr arrays:

```
.
└── dataset.zarr/
    ├── .zgroup
    ├── base
    │   ├── .zarray
    │   ├── .zattrs
    │   ├── 0.0.0
    │   └── ...etc
    └── downsampled/
        ├── .zgroup
        ├── 01/
        │   ├── .zarray
        │   ├── 0.0.0
        │   └── ...etc
        └── 02/
            ├── .zarray
            ├── 0.0.0
            └── ...etc
```

### CODE REVIEW

**Comment by manzt** [comment]
I'll add some fixtures and tests before merging anything, but it would be great to get your thoughts on this. I envision the cli being very minimal, something like: 

```
$ img2zarr convert <img-file-path>
$ img2zarr create-pyramid <output-from-above>
```

**Review by NHPatterson — COMMENTED** [review]
I think this looks good. I have just a couple concerns we can discuss below

https://github.com/hubmapconsortium/img2zarr/blob/a48a30ca01bb11a6e2f11f8849cabb9ba6ec52ad/img2zarr/create_pyramid.py#L24
**pyramid_group**: I'm not sure it makes sense to have the naming of the sub-group for image pyramid layers be a kwarg (```pyramid_group```). If we are to follow a set schema for the file format, this might be better for hard-coded. In some instances, like adding analyses to the root store, naming may be more appropriate. I don't think it is essential to change and I see that the cli doesn't have it optioned. On that note, we may want to the name to reflect the [OME standard](https://docs.openmicroscopy.org/ome-model/6.0.0/ome-tiff/specification.html#sub-resolutions) of ```sub-resolutions``` rather than ```downsampled```, but also not a major concern because downsampled may not be as ambiguous as sub-resolution. 

https://github.com/hubmapconsortium/img2zarr/blob/a48a30ca01bb11a6e2f11f8849cabb9ba6ec52ad/img2zarr/create_pyramid.py#L26
**Default tiling argument:** I'm not sure there's a reason yet to change how the tiling is performed at different sub-resolutions of the pyramid, but having the option is prudent for future unforeseen scenarios. That said, I think the default argument should be ```tile_size=None``` so that the chunk size is inherited from the base layer in the same way as ```max_level``` and ```dtype```. 

Also should ```dtype``` change between different layers of the pyramid?  This may cause problems with contrast settings at visualization if one image is 16-bit and a lower res is 8-bit. I think it's a great idea for performance if that is addressed. 


**Gaussian filtering** In a future version we should definitely implement Gaussian filtering of the layers before downsampling. I know this is a standard generally, but I wasn't sure why exactly why so I found some good basic [documentation](https://www.cs.toronto.edu/~mangas/teaching/320/slides/CSC320L10.pdf) Briefly, high frequency spatial signals in the image may create aliasing in the image when downsampling so the filter low passes them to prevent this. I don't this is necessary for this PR but is important. We can probably lean on ```skimage``` [here](https://github.com/scikit-image/scikit-image/blob/master/skimage/transform/pyramids.py) for the logic, and use [dask_image](http://image.dask.org/en/latest/) to do the [filtering](http://image.dask.org/en/latest/dask_image.ndfilters.html#dask_image.ndfilters.gaussian_filter).

**Comment by NHPatterson** [comment]
Let's also force the tiling to be a multiple of 16.

```python
if tile_size % 16:
    raise ValueError('tile_size ({}) must be a multiple of 16'.format(tile_size))
```

Also make sure the max level limit isn't hard coded to 512 tiles, see below.
```python
int(np.ceil(np.log2(np.maximum(y_size, x_size))) - np.log2(tile_size))
```

**Comment by manzt** [comment]
@NHPatterson I removed the `tile_size` argument for now. I think that we should just respect the base image chunking. My thought was that if this was provided (and it was different from the original chunking) we would create a new base and chunk that. 

I added a couple of tests just to make sure the cli is working, but better unit tests are definitely needed. `pytest` is much easier to use than `unittest` and should fit our needs well. Right now I create some output fixtures and then use these to just make sure some arrays are being created. In the future, we should probably just make a `fixtures/` dir with some _small_ sample base tile layers. Thoughts?

**Comment by NHPatterson** [comment]
Sounds good. Let's merge when you are ready.
https://github.com/hubmapconsortium/img2zarr/blob/895ab62879f21e083059acc3c8c705904d94c0cf/img2zarr/create_pyramid.py#L29

BTW, is this line appropriate for RGB/A images where the it will be YXC rather than CYX? What I've been trying to do is add axis order in the attributes.

**Comment by manzt** [comment]
>BTW, is this line appropriate for RGB/A images where the it will be YXC rather than CYX? What I've been trying to do is add axis order in the attributes.

Good catch. It's not --  I'm glad you brought it up. I was thinking we could look at the attributes for the base array and determine these explicitly. If not provided, we could try to make a sensible default? Something like how napari guesses if rgb based on the last dim?

**Comment by NHPatterson** [comment]
> > BTW, is this line appropriate for RGB/A images where the it will be YXC rather than CYX? What I've been trying to do is add axis order in the attributes.
> 
> Good catch. It's not -- I'm glad you brought it up. I was thinking we could look at the attributes for the base array and determine these explicitly. If not provided, we could try to make a sensible default? Something like how napari guesses if rgb based on the last dim?


Yeah seems solid if the length of the last dimension is 3 or 4, assume RGB.

**Pull request merged**
